name: db_client
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  coffee_domain:
    path: ../../packages/coffee_domain
  path_provider: ^2.1.5  
  sqflite: ^2.4.1
  
