name: coffee_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:  
  db_client:
    path: ../../packages/db_client
  http: ^1.3.0
  path_provider: ^2.1.5
